"""
FastAPI Router for the HealthAI Medical Chatbot.

Provides the POST /api/medical-chat endpoint powered by Agno Agent and OpenAI.
Independent from the RAG retrieval pipeline.
"""

from typing import Optional
from fastapi import APIRouter, HTTPException, status
from pydantic import BaseModel, Field

from backend.agents.medical_agent import generate_medical_chat_response

router = APIRouter(
    prefix="/api",
    tags=["Medical Chatbot"]
)


class MedicalChatRequest(BaseModel):
    """Payload for submitting a medical question to the HealthAI Medical Assistant."""
    message: str = Field(
        ...,
        min_length=1,
        description="General medical or health-related inquiry message",
        json_schema_extra={"example": "What are the symptoms of diabetes?"}
    )
    session_id: Optional[str] = Field(
        None,
        description="Unique session identifier for Agno SQLite conversation history",
        json_schema_extra={"example": "user-session-1234"}
    )


class MedicalChatResponse(BaseModel):
    """Response returned by the HealthAI Medical Assistant."""
    answer: str = Field(..., description="Educational answer generated by the medical agent")
    session_id: str = Field(..., description="Session identifier for Agno history tracking")
    status: str = Field(..., description="Status of the generation: 'success', 'empty_message', 'missing_api_key', or 'error'")
    agent: str = Field(default="HealthAI Medical Assistant", description="Name of the assisting agent")


@router.post(
    "/medical-chat",
    response_model=MedicalChatResponse,
    status_code=status.HTTP_200_OK,
    summary="Chat with HealthAI Medical Assistant",
    description=(
        "Submit general medical/health questions to the independent HealthAI Assistant. "
        "Answers are educational and follow strict safety boundaries (non-diagnostic, "
        "no prescriptions, no dosage adjustments, emergency escalations). "
        "Session history is automatically persisted in SQLite."
    ),
)
async def medical_chat_endpoint(payload: MedicalChatRequest) -> MedicalChatResponse:
    """
    Executes a medical conversation turn using the Agno Medical Agent.
    """
    cleaned_message = payload.message.strip()
    if not cleaned_message:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Message cannot be empty or whitespace only."
        )

    result = generate_medical_chat_response(
        message=cleaned_message,
        session_id=payload.session_id
    )

    return MedicalChatResponse(
        answer=result["answer"],
        session_id=result["session_id"],
        status=result["status"],
        agent=result.get("agent", "HealthAI Medical Assistant")
    )
